<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'f5f7c46bb5dca7df1373fe411945fe9d' => $baseDir . '/inc/hooks.php',
);
